console.log("I have"+1+2+"computers")
console.log(1+2+" computers are mine")
console.log("Sunday".indexOf("day"))
console.log("Sunday".substr(3,3))
console.log("Sunday".slice(3,6))
var x1 = "Sunday, Monday, Tuesday, Wednesday".split(",")
console.log(typeof x1, x1, Array.isArray(x1))
var x2 = "\t\n  abc def \n\t\n".trim()
console.log("x2="+x2)
"Sunday, Monday, Tuesday, Wednesday".split(",").forEach(p=>console.log(p.trim()))