
console.log(5 / 0, -5 / 0, Infinity == -Infinity)
console.log(Infinity > 5,Infinity > -Infinity)
console.log(5/0===Infinity, 5/0==Infinity)
var v1 = parseInt("5")
console.log(v1)
var v2 = parseInt("3.14")
console.log(v2)
var v3 = parseInt("3.999")
console.log(v3)
var v4 = parseFloat("5")
console.log(v4)
var v5 = parseInt("Hello")
console.log(v5, isNaN(v5))
console.log(isFinite(5/0), isFinite(-5/0), isFinite(5/1), isFinite(-5/1))