var x1 = Boolean(0)
console.log(typeof x1, x1)
var x2 = Boolean("")
console.log(typeof x2, x2)
var x3 = Boolean(NaN)
console.log(typeof x3, x3)
var x4 = Boolean(null)
console.log(typeof x4, x4)
var x5 = Boolean(undefined)
console.log(typeof x5, x5)
var x6 = Boolean(-1)
var x7 = Boolean(1)
var x8 = Boolean("true")
var x9 = Boolean("false")
console.log(typeof x6, x6, typeof x7, x7, typeof x8, x8, typeof x9, x9)